version: '{build}'
branches:
  only:
  - master
dotnet_csproj:
  patch: true
  file: Confused\Confused.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
artifacts:
- path: Confused\bin\Release\Confused.*.nupkg
  name: Confused
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") 
    { 
      $version = $env:appveyor_repo_tag_name.TrimStart("v"); 
      Update-AppveyorBuild -Version "$version"; 
    } else 
    {
      $build = $env:appveyor_build_number;
      Update-AppveyorBuild -Version "0.0.0.$build";
    }
    
install:
- cmd: dotnet restore
build_script:
- cmd: dotnet build Confused -c Release
- cmd: dotnet pack Confused -c Release
test_script:
- cmd: dotnet test Confused.Tests/Confused.Tests.csproj
deploy:
- provider: Environment
  name: Confused NuGet
  on:
    APPVEYOR_REPO_TAG: true